### ISSUE TITLE
tiles.MovingLetter.getSubscript deprecation in 3.5

### ISSUE THREAD

**Issue by scherven** [Innoviox/Pyrotor#8]
Python 3.5 and above has a unicode deprecation for \u2080-\u2089.

The attached file presents a possible fix using matplotlib and PIL.
[tk-matplotlib_test.txt](https://github.com/Innoviox/PyScrabble/files/504048/tk-matplotlib_test.txt)

**Comment by scherven** [comment]
The main question is if there should be a tiles.Subscript or if it should be directly implemented as try._except in tiles.MovingLetter.getSubscript

**Comment by scherven** [comment]
in the above attached file, line 20 should be math_to_image(r'$A_1$', buffer, dpi=100, format='png')

**Comment by scherven** [comment]
And actually lines 39-41 are unnecessary.

Please see remade file below.
[tk-matplotlib_test.txt](https://github.com/Innoviox/PyScrabble/files/504051/tk-matplotlib_test.txt)

**Comment by scherven** [comment]
yes a tiles.Subscript is the way to go I think

**Comment by Innoviox** [comment]
So yeah below find some code.
`import tkinter as tk
from matplotlib.mathtext import math_to_image
from io import BytesIO
from PIL import ImageTk, Image

class Subscript(tk.Frame):
    def __init__(self, frame, letter):
        tk.Frame.__init__(self, master)
        self.pack()
        self.scores = {"a": 1, "c": 3, "b": 3, "e": 1, "d": 2, "g": 2,
       "f": 4, "i": 1, "h": 4, "k": 5, "j": 8, "m": 3,
       "l": 1, "o": 1, "n": 1, "q": 10, "p": 3, "s": 1,
       "r": 1, "u": 1, "t": 1, "w": 4, "v": 4, "y": 4,
       "x": 8, "z": 10, "?" : 0}
        self.letter = letter
        self.createWidgets(letter.upper())



    def createWidgets(self, letter):
        buffer = BytesIO()
        math_to_image(r'$%s_%d$' % (letter, self.scores[letter.lower()]), buffer, dpi=100, format='png')
        buffer.seek(0)
        pimage= Image.open(buffer)
        image = ImageTk.PhotoImage(pimage)
        self.label = tk.Label(self,image=image)
        self.label.img = image
        self.label.pack(side="bottom")

root = tk.Tk()
root.geometry("%dx%d%+d%+d" % (300, 300, 0, 0))
app = Application(master=root)
app.mainloop()
`

**Comment by Innoviox** [comment]
`import tkinter as tk
from matplotlib.mathtext import math_to_image
from io import BytesIO
from PIL import ImageTk, Image

class Application(tk.Frame):
    def __init__(self, master=None):
        tk.Frame.__init__(self, master)
        self.pack()
        self.scores = {"a": 1, "c": 3, "b": 3, "e": 1, "d": 2, "g": 2,
       "f": 4, "i": 1, "h": 4, "k": 5, "j": 8, "m": 3,
       "l": 1, "o": 1, "n": 1, "q": 10, "p": 3, "s": 1,
       "r": 1, "u": 1, "t": 1, "w": 4, "v": 4, "y": 4,
       "x": 8, "z": 10, "?" : 0}
        self.createWidgets('A')



    def createWidgets(self, letter):
        buffer = BytesIO()
        math_to_image(r'$%s_%d$' % (letter, self.scores[letter.lower()]), buffer, dpi=100, format='png')
        buffer.seek(0)
        pimage= Image.open(buffer)
        image = ImageTk.PhotoImage(pimage)
        self.label = tk.Label(self,image=image)
        self.label.img = image
        self.label.pack(side="bottom")

root = tk.Tk()
root.geometry("%dx%d%+d%+d" % (300, 300, 0, 0))
app = Application(master=root)
app.mainloop()
`

**Comment by Innoviox** [comment]
`import tkinter as tk
from matplotlib.mathtext import math_to_image
from io import BytesIO
from PIL import ImageTk, Image`

`class Subscript(tk.Frame):
    def __init__(self, master=None):
        tk.Frame.__init__(self, master)
        self.pack()
        self.scores = {"a": 1, "c": 3, "b": 3, "e": 1, "d": 2, "g": 2,
       "f": 4, "i": 1, "h": 4, "k": 5, "j": 8, "m": 3,
       "l": 1, "o": 1, "n": 1, "q": 10, "p": 3, "s": 1,
       "r": 1, "u": 1, "t": 1, "w": 4, "v": 4, "y": 4,
       "x": 8, "z": 10, "?" : 0}
        self.createWidgets('A')`



`    def createWidgets(self, letter):
        buffer = BytesIO()
        math_to_image(r'$%s_%d$' % (letter, self.scores[letter.lower()]), buffer, dpi=100, format='png')
        buffer.seek(0)
        pimage= Image.open(buffer)
        image = ImageTk.PhotoImage(pimage)
        self.label = tk.Label(self,image=image)
        self.label.img = image
        self.label.pack(side="bottom")`

`root = tk.Tk()
root.geometry("%dx%d%+d%+d" % (300, 300, 0, 0))
app = Application(master=root)
app.mainloop()
`

**Comment by Innoviox** [comment]
[tk-matplotlib_test.txt](https://github.com/Innoviox/PyScrabble/files/504286/tk-matplotlib_test.txt)

**Comment by scherven** [comment]
[tk-matplotlib_test.txt](https://github.com/Innoviox/PyScrabble/files/504287/tk-matplotlib_test.txt)
